### PR TITLE
Missing energy

### PR DESCRIPTION
**Pull request by cbernet**
@drasal these are the mods we are talking about. 
I'm doing the PR to jlingema as I think it's easier to have a single person integrating podio-based software. But let me know what you think, we can also do otherwise. 
Cheers!

### CODE REVIEW

**Comment by jlingema** [comment]
Hi, I'm currently preparing the PRs for the migration to PODIO, should I include this or is there an ongoing discussion between the two of you?

**Comment by drasal** [comment]
Hi Joschka,
feel free to update the PODIO ... I will immediatelly test it on the Delphes module.

**Comment by jlingema** [comment]
Hi Zbynek,

The PR I'll do is with the same version of PODIO you are currently using. I meant the changes to MET in fcc-edm that Colin was suggesting and this PR refers to.

**Comment by drasal** [comment]
Joschka,

sure, I do understand ... Please, change the MET according to Colin's suggestion.

**Pull request merged**
